export const DEFAULT_INTERNAL_ERROR = 'An internal error occurred. Please try again later.';
export const JWT_SECRET_NOT_CONFIGURED = 'JWT secret is not configured. Please check your environment variables.';
export const FAILED_TO_GENERATE_TOKEN = 'Failed to generate token. Please try again later.';
export const UNAUTHORIZED = 'Unauthorized access. Please log in again.';
export const INVALID_TOKEN_FORMAT = 'Invalid token format. Please provide a valid token.';
export const NO_USER_FOUND = 'No user found with the provided credentials. Please check your username and password.';
export const BAD_REQUEST = 'Bad request. Please check your input and try again.';
export const NO_USER_PAYLOAD = 'No user payload provided. Please provide a valid user payload.';
export const USER_ALREADY_EXISTS = (username : string ) => `User with username ${username} already exists. Please choose a different username.`;
export const USER_EMAIL_ALREADY_EXISTS = (email : string ) => `User with email ${email} already exists. Please choose a different email.`;
export const CLIENT_EMAIL_ALREADY_EXISTS = (email : string ) => `Client with email ${email} already exists. Please choose a different email.`;
export const CLIENT_PHONE_ALREADY_EXISTS = (phone : string ) => `Client with phone ${phone} already exists. Please choose a different phone number.`;
export const PHONE_ALREADY_EXISTS = (phone : string ) => `Phone number ${phone} already exists. Please choose a different phone number.`;
export const EMAIL_ALREADY_EXISTS = (email : string ) => `Email ${email} already exists. Please choose a different email.`;
export const VALIDATION_ERROR = (errorMessage : string) => `Validation error: ${errorMessage}`;
export const SERVER_ERROR = (errorMessage : unknown) => `Server Error -> ${errorMessage}`;
export const CLIENT_NOT_FOUND = (id: number | string) => `Client with ID ${id} not found. Please check the ID and try again.`;
export const NOT_FOUND = (id: number | string) => `Resource with ID ${id} not found. Please check the ID and try again.`;
