name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  run-build:
    runs-on: deere-ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Run build
        run: |
          npm install
          npm run build
